import Link from "next/link"
import Head from "next/head"
import style from "./login.module.scss"
import { useState } from "react"
import next from "next"
import { useRouter } from "next/router"
import { login } from "../../api/services"

export default function Login({ allData }) {
  const [name, setName] = useState("")
  const [pwd, setPwd] = useState(null)
  const router = useRouter()

  return (
    <div>
      <Head>
        <title>login page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>当前环境：{process.env.NEXT_PUBLIC_MODE}</div>
      <div>
        账号
        <input
          type="text"
          onInput={(e) => {
            console.log(e.target.value)
            setName(e.target.value)
          }}
        />
      </div>
      <div>
        密码
        <input
          type="text"
          onInput={(e) => {
            console.log(e.target.value)
            setPwd(e.target.value)
          }}
        />
      </div>
      <div
        onClick={async () => {
          login({ userId: 12312, pwd: "xxx" })
            .then((res) => {
              console.log(res)
              localStorage.setItem("token", res.token)
              const params = new URLSearchParams(document.location.search)
              const backUrl = params.get("backUrl")
              if (backUrl) {
                window.location.href = backUrl
              } else {
                router.push("/user")
              }
            })
            .catch((error) => {
              console.log(error)
            })
        }}
      >
        登录
      </div>
    </div>
  )
}
