import Link from 'next/link'
import Head from 'next/head'
import style from './login.module.scss'
import { useState } from 'react'
import next from 'next'
import { useRouter } from 'next/router'

export default function Login({ allData }) {
  console.log("🚀 ~ file: index.js ~ line 6 ~ Login ~ allData", allData)
  const [name, setName] = useState("")
  const [pwd, setPwd] = useState(null)
  const router = useRouter()

  return <div>
    <Head>
      <title>login page</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div>当前环境：{process.env.NEXT_PUBLIC_MODE}</div>
    <div>
      账号
      <input type="text" onInput={(e) => {
        console.log(e.target.value);
        setName(e.target.value)
      }} />
    </div>
    <div>
      密码
      <input type="text" onInput={(e) => {
        console.log(e.target.value);
        setPwd(e.target.value)
      }} />
    </div>
    <div onClick={async () => {
      console.log(name, pwd);
      const res = await fetch('/api/user/login', { headers: { 'Content-Type': 'application/json;charset=UTF-8' }, method: 'post', body: JSON.stringify({ userId: 12312, pwd: 'xxx' }) })
      res.json().then((res) => {
        console.log(res.token);
        localStorage.setItem('token', res.token)
        router.push('/user')
      })
    }}>登录</div>
  </div>
}

