import Head from 'next/head'
import { useRouter } from 'next/router'
import Link from 'next/link'
export default function Home({ allData }) {
  console.log("🚀 ~ file: index.js ~ line 6 ~ Home ~ allData", allData)
  const router = useRouter()

  return (
    <div>
      <Head>
        <title>1Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div onClick={async () => {
        const res = await fetch('/api/user', { headers: { 'Content-Type': 'application/json;charset=UTF-8' }, method: 'get' })
        res.json().then((res) => {
          console.log(res);
        })
      }}>123</div>
      {
        allData?.map((item) => {
          return <div key={item.id} onClick={() => {
            router.push({
              pathname: '/user/[pid]',
              query: { pid: item.id },
            })
          }}>{`${item.name || 'xxxxxxxxxxxx'}:${item.address || "22222222222222"}`}
          </div>
        })
      }
    </div>
  )
}

export async function getServerSideProps(context) {
  const cookies = context.req.headers.cookie;
  const token = context.req.cookies['token']
  console.log("🚀 ~ file: index.js ~ line 33 ~ getServerSideProps ~ token", token)
  console.log("🚀 ~ file: index.js ~ line 27 ~ getServerSideProps ~ cookies", cookies)
  // await new Promise(((resolve) => {
  //   setTimeout(() => {
  //     resolve({
  //       props: {
  //         name: 123,
  //         allData: 11111111111
  //       }
  //     })
  //   }, 2000);
  // }))
  let res = null
  let arr = []
  try {
    res = await fetch('http://localhost:8020/user', { method: 'get', headers: { token: token } })
    console.log(res);
    if (res.status === 200) {
      arr = await res.json()
    }
  } catch (error) {
    console.log(error);
  }
  console.log("🚀 ~ file: index.js ~ line 34 ~ getServerSideProps ~ res", res)
  return {
    props: {
      name: 123,
      allData: arr
    }
  }
}