import Head from "next/head"
import { useRouter } from "next/router"
import Link from "next/link"
import { getUserList } from "../../api/services"
import { useInit } from "../hooks/init.hooks"
import { useEffect } from "react"
import { Button, message, notification } from "antd"
import style from "./index.module.scss"

export default function User({ allData, user }) {
  const router = useRouter()
  const { flag } = useInit(user)
  useEffect(() => {
    console.log("123")
  }, [])

  if (!flag) {
    return <div>forbid</div>
  }

  return (
    <div className={style["container"]}>
      <Head>
        <title>1Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        onClick={async () => {
          const res = await fetch("/api/user", {
            headers: { "Content-Type": "application/json;charset=UTF-8" },
            method: "get",
          })
          res.json().then((res) => {
            console.log(res)
          })
        }}
      >
        123
      </div>
      {allData?.map((item) => {
        return (
          <div
            key={item.id}
            onClick={() => {
              router.push({
                pathname: "/user/[pid]",
                query: { pid: item.id },
              })
            }}
          >
            {`${item.name || "xxxxxxxxxxxx"}:${
              item.address || "22222222222222"
            }`}
          </div>
        )
      })}
    </div>
  )
}

export async function getServerSideProps(context) {
  const token = context.req.cookies["token"]
  let allData = []
  const user = {}
  try {
    await getUserList({ headers: { token } }).then((res) => {
      console.log(res)
      allData = res
      user.signed = true
    })
  } catch (error) {
    //
  }
  return {
    props: {
      name: 123,
      allData,
      user,
    },
  }
}
